### PR TITLE
Portfolio Deployment

### PR DESCRIPTION
**Pull request by manzitresor**
Added Link in readme file in Portfolio Project

### CODE REVIEW

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @manzitresor 👋👋👋, 

tryagain


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Github flow have been used👍.


## Required Changes ♻️

- [ ] Just as required in this milestone, Kindly update your readme file (live demo section) with the link to your deployed project👍.
image

- [ ] I noticed the link to the logo on your readme file is broken, kindly fix it as it gives your project a less professional look🥲

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by manzitresor** [comment]
@Ibizugbe 
May be I need more clarification on this required changes because if you see well on this blanch on the read me file I have added
live demo in line 57 and it is working. 
if possible you can check it again

**Comment by Ibizugbe** [comment]
Hello @manzitresor 👋👋 Very sorry about the inconviniences, I actually didn't see it initially🥲. I suggest you kindly follow the template and add it to the `live demo` section of your readme file to make it more visible👍.

**Comment by manzitresor** [comment]
@Ibizugbe ok thanks for clarification now I have made those changes . 
thank you!!

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @manzitresor 👋👋, 

tryagain


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights✅✅✅

- [x] Nice job adding the link to your live demo in the right section of the readme👍.
- [x] Project have been deployed with github pages and everything works well👍.


 ## Required Changes ♻️

- [ ] Just as requested in the previous review, the link to the logo on your readme file is broken🥲, Kindly fix it or take it away as it is giving your project a less professional look👍.
image


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by wickathou** [comment]
Hi @manzitresor  , 

# Congratulations! 🎉

## Your project is complete!

### It's time to merge it :trophy:  

## Optional suggestions
- [ ] Use descriptive commit messages for your coming projects, as it helps to keep your work well documented and it can help when using git commands such as `git bisect`
- [ ] Make your Pull Request description more detailed to explain what the reviewer should expect for this review summarizing the work done

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
