### PR TITLE
Preserve data in the browser

### PR DESCRIPTION
**Pull request by manzitresor**
This part contains preserve data in browser using Local storage to store input

### CODE REVIEW

**Review by m05e5 — CHANGES_REQUESTED** [review]
Hi Team , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

 This is a pair programming activity please kindly make sure that every group member participates.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by wayungi — COMMENTED** [review]
Hi  @manzitresor , 
image

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] You have submitted a collaboration project done alone. **Please attach a screenshot of your communication with student success allowing you to do the project solo**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by manzitresor** [comment]
Student Success has permitted me to continue working on this project solo. If you have any questions please reach out to Marco: [success@microverse.org](mailto:success@microverse.org)

**Comment by christianbiring1** [comment]
> Student Success has permitted me to continue working on this project solo. If you have any questions please reach out to Marco: [success@microverse.org](mailto:success@microverse.org)

@manzitresor  Great for reaching out to the student success about your case :+1:

**Review by christianbiring1 — APPROVED** [review]
Hi @manzitresor , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 

## Highlights
- [ ] Great work on preserving and retrieving the user inputs correctly in form the local storage on page load :+1: 
- [ ] Descriptive PR `title` and `summary` :+1: 
- [ ] All linters checks are green :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by manzitresor** [comment]
@christianbiring1 
Thank you so much for the review 🥇 !!

**Pull request merged**
